site_name: Meu Site Docs
#site_dir: docs
#site_url: https://seu-usuario.github.io/seu-repositorio/
#repo_url: https://github.com/seu-usuario/seu-repositorio

theme:
  name: material

nav:
  - Home: index.md
  - Sobre: sobre.md
  - Contato: contato.md

#plugins:
#  - search
